// src/contexts/LanguageContext.tsx

import React, { createContext, useContext, useMemo, useState, useEffect, useCallback } from "react";
import storage from "../utils/persistentStorage";

export type Language = "fr" | "en" | "es" | "pt" | "zh" | "ja";

type LanguageCtx = {
  language: Language;
  setLanguage: (l: Language) => Promise<void>;
  t: (key: string) => string;
};

const STORAGE_KEY = "app_language";

const LANGUAGE_NAMES: Record<Language, string> = {
  fr: "Français",
  en: "English", 
  es: "Español",
  pt: "Português",
  zh: "中文",
  ja: "日本語",
};

const LANGUAGE_FLAGS: Record<Language, string> = {
  fr: "🇫🇷",
  en: "🇺🇸",
  es: "🇪🇸", 
  pt: "🇵🇹",
  zh: "🇨🇳",
  ja: "🇯🇵",
};

const SUPPORTED_LANGUAGES: Language[] = ["fr", "en", "es", "pt", "zh", "ja"];

// Traductions
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.advisor": "Conseiller",
    "nav.stats": "Statistiques", 
    "nav.settings": "Paramètres",
    
    // Home Screen
    "home.title": "CashHeal",
    "home.subtitle": "Gérez vos finances intelligemment",
    "home.balance": "Solde",
    "home.available": "Disponible",
    "home.spent": "Dépensé",
    "home.budget": "Budget",
    "home.add_expense": "Ajouter une dépense",
    "home.categories": "Catégories",
    "home.food": "Nourriture",
    "home.shopping": "Shopping",
    "home.leisure": "Loisirs",
    "home.welcome_heading": "Bienvenue !",
    "home.greeting": "Bonjour 👋",
    "home.welcome_subtitle": "Prêt à soigner vos finances ?",
    "home.today_spent": "Tu as dépensé aujourd'hui",
    "home.daily_budget": "Budget du jour",
    "home.remaining_today": "Il te reste {amount} pour aujourd'hui.",
    "home.period_day": "Jour",
    "home.period_2weeks": "2 semaines",
    "home.period_month": "Mois",
    "home.weekly_average": "Moyenne cette semaine",
    "home.prediction": "Prédiction",
    "home.dashboard_title": "Tableau de bord",
    "home.modal_add_title": "Ajouter une dépense",
    "home.modal_remove_title": "Annuler une dépense",
    "home.modal_category": "Catégorie",
    "home.modal_amount": "Montant",
    "home.modal_amount_placeholder": "Montant",
    
    // Budget Advisor
    "advisor.title": "Conseiller Budgétaire",
    "advisor.subtitle": "Créons votre plan financier personnalisé",
    "advisor.monthly_budget": "Quel est votre budget mensuel ?",
    "advisor.rent": "Quel est votre loyer mensuel ?",
    "advisor.daily_spending": "Combien voulez-vous dépenser par jour ?",
    "advisor.weekly_spending": "Combien voulez-vous dépenser par semaine ?",
    "advisor.biweekly_spending": "Combien voulez-vous dépenser toutes les 2 semaines ?",
    "advisor.monthly_spending": "Combien voulez-vous dépenser par mois ?",
    "advisor.savings_goal": "Quel est votre objectif d'épargne ?",
    "advisor.savings_30": "Sécurité maximale (30% d'épargne)",
    "advisor.savings_balanced": "Juste milieu (15% d'épargne)",
    "advisor.savings_invest": "Investissement (5% d'épargne)",
    "advisor.calculate": "Calculer mon plan",
    "advisor.save": "Sauvegarder",
    "advisor.continue": "Continuer",
    "advisor.back": "Retour",
    "advisor.result_title": "Votre plan budgétaire",
    "advisor.fixed_charges": "Charges fixes",
    "advisor.available_spending": "Disponible pour dépenser",
    "advisor.daily_budget": "Budget quotidien",
    "advisor.weekly_budget": "Budget hebdomadaire",
    "advisor.biweekly_budget": "Budget bi-hebdomadaire",
    
    // Settings
    "settings.title": "Paramètres",
    "settings.currency": "Devise",
    "settings.language": "Langue",
    "settings.country": "Pays",
    "settings.notifications": "Notifications",
    "settings.biometric": "Authentification biométrique",
    "settings.dark_mode": "Mode sombre",
    "settings.personal_info": "Informations personnelles",
    "settings.logout": "Se déconnecter",
    "settings.subtitle": "Personnalisez votre expérience",
    "settings.section_preferences": "Préférences",
    "settings.section_security": "Sécurité",
    "settings.section_appearance": "Apparence",
    "settings.section_account": "Compte",
    "settings.section_actions": "Actions",
    "settings.choose_language": "Sélectionnez votre langue préférée",
    "settings.choose_country": "Sélectionnez votre pays",
    "settings.currency_modal_title": "Choisir une devise",
    "settings.currency_modal_use_saved": "Utiliser la devise du plan sauvegardé",
    "settings.push_notifications_title": "Notifications push",
    "settings.push_notifications_subtitle": "Recevoir des notifications sur vos dépenses",
    "settings.biometric_title": "Authentification biométrique",
    "settings.biometric_subtitle": "Utiliser Face ID ou Touch ID",
    "settings.dark_mode_title": "Mode sombre",
    "settings.dark_mode_subtitle": "Activer le thème sombre",
    "settings.personal_info_title": "Informations personnelles",
    "settings.personal_info_subtitle": "Modifier votre profil",
    "settings.personal_info_alert_title": "Profil",
    "settings.personal_info_alert_body": "Fonctionnalité à venir",
    "settings.logout_title": "Se déconnecter",
    "settings.logout_subtitle": "Déconnexion de votre compte",
    "settings.delete_account_title": "Supprimer le compte",
    "settings.delete_account_subtitle": "Supprimer définitivement votre compte",
    
    // Common
    "common.save": "Sauvegarder",
    "common.cancel": "Annuler",
    "common.confirm": "Confirmer",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.loading": "Chargement...",
    "home.prediction_message_day_default": "Tu as dépensé moins que prévu aujourd'hui, continue ainsi !",
    "home.prediction_message_2weeks_default": "Tu es sur la bonne voie pour rester sous ton budget.",
    "home.prediction_message_month_default": "Tu peux viser un peu plus d'épargne ce mois-ci.",
    "home.category_food": "Nourriture",
    "home.category_shopping": "Shopping",
    "home.category_leisure": "Loisirs",
    "details.title": "Plan budgétaire rapide",
    "details.monthly_income_label": "Revenu mensuel (EUR)",
    "details.monthly_income_placeholder": "Ex. 2500",
    "details.savings_target_label": "Objectif d’épargne mensuel",
    "details.savings_target_placeholder": "Ex. 700",
    "details.calculate_button": "Calculer",
    "details.recommendations_title": "Recommandations",
    "details.recommendations_monthly": "Dépenses mensuelles : {amount}",
    "details.recommendations_weekly": "Dépenses hebdo : {amount}",
    "details.recommendations_daily": "Dépenses quotidiennes : {amount}",
    "details.go_to_advisor": "Aller au plan détaillé",
  },
  
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.advisor": "Advisor",
    "nav.stats": "Statistics",
    "nav.settings": "Settings",
    
    // Home Screen
    "home.title": "CashHeal",
    "home.subtitle": "Manage your finances smartly",
    "home.balance": "Balance",
    "home.available": "Available",
    "home.spent": "Spent",
    "home.budget": "Budget",
    "home.add_expense": "Add expense",
    "home.categories": "Categories",
    "home.food": "Food",
    "home.shopping": "Shopping",
    "home.leisure": "Leisure",
    "home.welcome_heading": "Welcome!",
    "home.greeting": "Hello 👋",
    "home.welcome_subtitle": "Ready to heal your finances?",
    "home.today_spent": "You've spent today",
    "home.daily_budget": "Today's budget",
    "home.remaining_today": "You still have {amount} for today.",
    "home.period_day": "Day",
    "home.period_2weeks": "2 weeks",
    "home.period_month": "Month",
    "home.weekly_average": "Average this week",
    "home.prediction": "Prediction",
    "home.dashboard_title": "Dashboard",
    "home.modal_add_title": "Add an expense",
    "home.modal_remove_title": "Remove an expense",
    "home.modal_category": "Category",
    "home.modal_amount": "Amount",
    "home.modal_amount_placeholder": "Amount",
    
    // Budget Advisor
    "advisor.title": "Budget Advisor",
    "advisor.subtitle": "Let's create your personalized financial plan",
    "advisor.monthly_budget": "What is your monthly budget?",
    "advisor.rent": "What is your monthly rent?",
    "advisor.daily_spending": "How much do you want to spend per day?",
    "advisor.weekly_spending": "How much do you want to spend per week?",
    "advisor.biweekly_spending": "How much do you want to spend every 2 weeks?",
    "advisor.monthly_spending": "How much do you want to spend per month?",
    "advisor.savings_goal": "What is your savings goal?",
    "advisor.savings_30": "Maximum security (30% savings)",
    "advisor.savings_balanced": "Balanced (15% savings)",
    "advisor.savings_invest": "Investment (5% savings)",
    "advisor.calculate": "Calculate my plan",
    "advisor.save": "Save",
    "advisor.continue": "Continue",
    "advisor.back": "Back",
    "advisor.result_title": "Your budget plan",
    "advisor.fixed_charges": "Fixed charges",
    "advisor.available_spending": "Available for spending",
    "advisor.daily_budget": "Daily budget",
    "advisor.weekly_budget": "Weekly budget",
    "advisor.biweekly_budget": "Bi-weekly budget",
    
    // Settings
    "settings.title": "Settings",
    "settings.currency": "Currency",
    "settings.language": "Language",
    "settings.country": "Country",
    "settings.notifications": "Notifications",
    "settings.biometric": "Biometric authentication",
    "settings.dark_mode": "Dark mode",
    "settings.personal_info": "Personal information",
    "settings.logout": "Logout",
    "settings.subtitle": "Personalise your experience",
    "settings.section_preferences": "Preferences",
    "settings.section_security": "Security",
    "settings.section_appearance": "Appearance",
    "settings.section_account": "Account",
    "settings.section_actions": "Actions",
    "settings.choose_language": "Select your preferred language",
    "settings.choose_country": "Select your country",
    "settings.currency_modal_title": "Choose a currency",
    "settings.currency_modal_use_saved": "Use saved plan currency",
    "settings.push_notifications_title": "Push notifications",
    "settings.push_notifications_subtitle": "Receive spending alerts",
    "settings.biometric_title": "Biometric authentication",
    "settings.biometric_subtitle": "Use Face ID or Touch ID",
    "settings.dark_mode_title": "Dark mode",
    "settings.dark_mode_subtitle": "Enable dark theme",
    "settings.personal_info_title": "Personal information",
    "settings.personal_info_subtitle": "Edit your profile",
    "settings.personal_info_alert_title": "Profile",
    "settings.personal_info_alert_body": "Feature coming soon",
    "settings.logout_title": "Logout",
    "settings.logout_subtitle": "Sign out of your account",
    "settings.delete_account_title": "Delete account",
    "settings.delete_account_subtitle": "Permanently delete your account",
    
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.error": "Error",
    "common.success": "Success",
    "common.loading": "Loading...",
    "home.prediction_message_day_default": "You spent less than expected today, keep it up!",
    "home.prediction_message_2weeks_default": "You're on track to stay under budget.",
    "home.prediction_message_month_default": "You can aim for a bit more savings this month.",
    "home.category_food": "Food",
    "home.category_shopping": "Shopping",
    "home.category_leisure": "Leisure",
    "details.title": "Quick budget plan",
    "details.monthly_income_label": "Monthly income (EUR)",
    "details.monthly_income_placeholder": "Ex. 2500",
    "details.savings_target_label": "Monthly savings goal",
    "details.savings_target_placeholder": "Ex. 700",
    "details.calculate_button": "Calculate",
    "details.recommendations_title": "Recommendations",
    "details.recommendations_monthly": "Monthly spending: {amount}",
    "details.recommendations_weekly": "Weekly spending: {amount}",
    "details.recommendations_daily": "Daily spending: {amount}",
    "details.go_to_advisor": "Go to detailed plan",
  },
  
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.advisor": "Asesor",
    "nav.stats": "Estadísticas",
    "nav.settings": "Configuración",
    
    // Home Screen
    "home.title": "CashHeal",
    "home.subtitle": "Gestiona tus finanzas inteligentemente",
    "home.balance": "Saldo",
    "home.available": "Disponible",
    "home.spent": "Gastado",
    "home.budget": "Presupuesto",
    "home.add_expense": "Agregar gasto",
    "home.categories": "Categorías",
    "home.food": "Comida",
    "home.shopping": "Compras",
    "home.leisure": "Ocio",
    "home.welcome_heading": "¡Bienvenido!",
    "home.greeting": "Hola 👋",
    "home.welcome_subtitle": "¿Listo para sanar tus finanzas?",
    "home.today_spent": "Has gastado hoy",
    "home.daily_budget": "Presupuesto de hoy",
    "home.remaining_today": "Te quedan {amount} para hoy.",
    "home.period_day": "Día",
    "home.period_2weeks": "2 semanas",
    "home.period_month": "Mes",
    "home.weekly_average": "Promedio esta semana",
    "home.prediction": "Predicción",
    "home.dashboard_title": "Panel de control",
    "home.modal_add_title": "Agregar un gasto",
    "home.modal_remove_title": "Eliminar un gasto",
    "home.modal_category": "Categoría",
    "home.modal_amount": "Monto",
    "home.modal_amount_placeholder": "Monto",
    
    // Budget Advisor
    "advisor.title": "Asesor Presupuestario",
    "advisor.subtitle": "Creemos tu plan financiero personalizado",
    "advisor.monthly_budget": "¿Cuál es tu presupuesto mensual?",
    "advisor.rent": "¿Cuál es tu alquiler mensual?",
    "advisor.daily_spending": "¿Cuánto quieres gastar por día?",
    "advisor.weekly_spending": "¿Cuánto quieres gastar por semana?",
    "advisor.biweekly_spending": "¿Cuánto quieres gastar cada 2 semanas?",
    "advisor.monthly_spending": "¿Cuánto quieres gastar por mes?",
    "advisor.savings_goal": "¿Cuál es tu objetivo de ahorro?",
    "advisor.savings_30": "Máxima seguridad (30% ahorro)",
    "advisor.savings_balanced": "Equilibrado (15% ahorro)",
    "advisor.savings_invest": "Inversión (5% ahorro)",
    "advisor.calculate": "Calcular mi plan",
    "advisor.save": "Guardar",
    "advisor.continue": "Continuar",
    "advisor.back": "Atrás",
    "advisor.result_title": "Tu plan presupuestario",
    "advisor.fixed_charges": "Cargos fijos",
    "advisor.available_spending": "Disponible para gastar",
    "advisor.daily_budget": "Presupuesto diario",
    "advisor.weekly_budget": "Presupuesto semanal",
    "advisor.biweekly_budget": "Presupuesto quincenal",
    
    // Settings
    "settings.title": "Configuración",
    "settings.currency": "Moneda",
    "settings.language": "Idioma",
    "settings.country": "País",
    "settings.notifications": "Notificaciones",
    "settings.biometric": "Autenticación biométrica",
    "settings.dark_mode": "Modo oscuro",
    "settings.personal_info": "Información personal",
    "settings.logout": "Cerrar sesión",
    "settings.subtitle": "Personaliza tu experiencia",
    "settings.section_preferences": "Preferencias",
    "settings.section_security": "Seguridad",
    "settings.section_appearance": "Apariencia",
    "settings.section_account": "Cuenta",
    "settings.section_actions": "Acciones",
    "settings.choose_language": "Selecciona tu idioma preferido",
    "settings.choose_country": "Selecciona tu país",
    "settings.currency_modal_title": "Elegir una moneda",
    "settings.currency_modal_use_saved": "Usar la moneda del plan guardado",
    "settings.push_notifications_title": "Notificaciones push",
    "settings.push_notifications_subtitle": "Recibir notificaciones sobre tus gastos",
    "settings.biometric_title": "Autenticación biométrica",
    "settings.biometric_subtitle": "Usar Face ID o Touch ID",
    "settings.dark_mode_title": "Modo oscuro",
    "settings.dark_mode_subtitle": "Activar el tema oscuro",
    "settings.personal_info_title": "Información personal",
    "settings.personal_info_subtitle": "Modificar tu perfil",
    "settings.personal_info_alert_title": "Perfil",
    "settings.personal_info_alert_body": "Función próximamente",
    "settings.logout_title": "Cerrar sesión",
    "settings.logout_subtitle": "Cerrar tu cuenta",
    "settings.delete_account_title": "Eliminar cuenta",
    "settings.delete_account_subtitle": "Eliminar tu cuenta definitivamente",
    
    // Common
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.loading": "Cargando...",
    "home.prediction_message_day_default": "Has gastado menos de lo previsto hoy, ¡sigue así!",
    "home.prediction_message_2weeks_default": "Vas por buen camino para mantenerte bajo el presupuesto.",
    "home.prediction_message_month_default": "Puedes apuntar a un poco más de ahorro este mes.",
    "home.category_food": "Comida",
    "home.category_shopping": "Compras",
    "home.category_leisure": "Ocio",
    "details.title": "Plan de presupuesto rápido",
    "details.monthly_income_label": "Ingresos mensuales (EUR)",
    "details.monthly_income_placeholder": "Ej. 2500",
    "details.savings_target_label": "Objetivo de ahorro mensual",
    "details.savings_target_placeholder": "Ej. 700",
    "details.calculate_button": "Calcular",
    "details.recommendations_title": "Recomendaciones",
    "details.recommendations_monthly": "Gastos mensuales: {amount}",
    "details.recommendations_weekly": "Gastos semanales: {amount}",
    "details.recommendations_daily": "Gastos diarios: {amount}",
    "details.go_to_advisor": "Ir al plan detallado",
  },
  
  pt: {
    // Navigation
    "nav.home": "Início",
    "nav.advisor": "Consultor",
    "nav.stats": "Estatísticas",
    "nav.settings": "Configurações",
    
    // Home Screen
    "home.title": "CashHeal",
    "home.subtitle": "Gerencie suas finanças inteligentemente",
    "home.balance": "Saldo",
    "home.available": "Disponível",
    "home.spent": "Gasto",
    "home.budget": "Orçamento",
    "home.add_expense": "Adicionar despesa",
    "home.categories": "Categorias",
    "home.food": "Comida",
    "home.shopping": "Compras",
    "home.leisure": "Lazer",
    "home.welcome_heading": "Bem-vindo!",
    "home.greeting": "Olá 👋",
    "home.welcome_subtitle": "Pronto para cuidar das suas finanças?",
    "home.today_spent": "Você gastou hoje",
    "home.daily_budget": "Orçamento de hoje",
    "home.remaining_today": "Você ainda tem {amount} para hoje.",
    "home.period_day": "Dia",
    "home.period_2weeks": "2 semanas",
    "home.period_month": "Mês",
    "home.weekly_average": "Média desta semana",
    "home.prediction": "Previsão",
    "home.dashboard_title": "Painel",
    "home.modal_add_title": "Adicionar despesa",
    "home.modal_remove_title": "Remover despesa",
    "home.modal_category": "Categoria",
    "home.modal_amount": "Quantia",
    "home.modal_amount_placeholder": "Quantia",
    
    // Budget Advisor
    "advisor.title": "Consultor Orçamentário",
    "advisor.subtitle": "Vamos criar seu plano financeiro personalizado",
    "advisor.monthly_budget": "Qual é seu orçamento mensal?",
    "advisor.rent": "Qual é seu aluguel mensal?",
    "advisor.daily_spending": "Quanto você quer gastar por dia?",
    "advisor.weekly_spending": "Quanto você quer gastar por semana?",
    "advisor.biweekly_spending": "Quanto você quer gastar a cada 2 semanas?",
    "advisor.monthly_spending": "Quanto você quer gastar por mês?",
    "advisor.savings_goal": "Qual é seu objetivo de poupança?",
    "advisor.savings_30": "Máxima segurança (30% poupança)",
    "advisor.savings_balanced": "Equilibrado (15% poupança)",
    "advisor.savings_invest": "Investimento (5% poupança)",
    "advisor.calculate": "Calcular meu plano",
    "advisor.save": "Salvar",
    "advisor.continue": "Continuar",
    "advisor.back": "Voltar",
    "advisor.result_title": "Seu plano orçamentário",
    "advisor.fixed_charges": "Custos fixos",
    "advisor.available_spending": "Disponível para gastar",
    "advisor.daily_budget": "Orçamento diário",
    "advisor.weekly_budget": "Orçamento semanal",
    "advisor.biweekly_budget": "Orçamento quinzenal",
    
    // Settings
    "settings.title": "Configurações",
    "settings.currency": "Moeda",
    "settings.language": "Idioma",
    "settings.country": "País",
    "settings.notifications": "Notificações",
    "settings.biometric": "Autenticação biométrica",
    "settings.dark_mode": "Modo escuro",
    "settings.personal_info": "Informações pessoais",
    "settings.logout": "Sair",
    "settings.subtitle": "Personalize sua experiência",
    "settings.section_preferences": "Preferências",
    "settings.section_security": "Segurança",
    "settings.section_appearance": "Aparência",
    "settings.section_account": "Conta",
    "settings.section_actions": "Ações",
    "settings.choose_language": "Selecione seu idioma preferido",
    "settings.choose_country": "Selecione seu país",
    "settings.currency_modal_title": "Escolher uma moeda",
    "settings.currency_modal_use_saved": "Usar moeda do plano salvo",
    "settings.push_notifications_title": "Notificações push",
    "settings.push_notifications_subtitle": "Receber alertas de gastos",
    "settings.biometric_title": "Autenticação biométrica",
    "settings.biometric_subtitle": "Usar Face ID ou Touch ID",
    "settings.dark_mode_title": "Modo escuro",
    "settings.dark_mode_subtitle": "Ativar tema escuro",
    "settings.personal_info_title": "Informações pessoais",
    "settings.personal_info_subtitle": "Editar seu perfil",
    "settings.personal_info_alert_title": "Perfil",
    "settings.personal_info_alert_body": "Funcionalidade em breve",
    "settings.logout_title": "Sair",
    "settings.logout_subtitle": "Desconectar da sua conta",
    "settings.delete_account_title": "Excluir conta",
    "settings.delete_account_subtitle": "Excluir sua conta permanentemente",
    
    // Common
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.loading": "Carregando...",
    "home.prediction_message_day_default": "Você gastou menos do que o previsto hoje, continue assim!",
    "home.prediction_message_2weeks_default": "Você está no caminho certo para ficar abaixo do orçamento.",
    "home.prediction_message_month_default": "Você pode buscar um pouco mais de economia este mês.",
    "home.category_food": "Comida",
    "home.category_shopping": "Compras",
    "home.category_leisure": "Lazer",
    "details.title": "Plano rápido de orçamento",
    "details.monthly_income_label": "Renda mensal (EUR)",
    "details.monthly_income_placeholder": "Ex. 2500",
    "details.savings_target_label": "Meta de poupança mensal",
    "details.savings_target_placeholder": "Ex. 700",
    "details.calculate_button": "Calcular",
    "details.recommendations_title": "Recomendações",
    "details.recommendations_monthly": "Gastos mensais: {amount}",
    "details.recommendations_weekly": "Gastos semanais: {amount}",
    "details.recommendations_daily": "Gastos diários: {amount}",
    "details.go_to_advisor": "Ir para o plano detalhado",
  },
  
  zh: {
    // Navigation
    "nav.home": "首页",
    "nav.advisor": "顾问",
    "nav.stats": "统计",
    "nav.settings": "设置",
    
    // Home Screen
    "home.title": "CashHeal",
    "home.subtitle": "智能管理您的财务",
    "home.balance": "余额",
    "home.available": "可用",
    "home.spent": "已花费",
    "home.budget": "预算",
    "home.add_expense": "添加支出",
    "home.categories": "类别",
    "home.food": "食物",
    "home.shopping": "购物",
    "home.leisure": "休闲",
    "home.welcome_heading": "欢迎！",
    "home.greeting": "你好 👋",
    "home.welcome_subtitle": "准备好护理你的财务了吗？",
    "home.today_spent": "你今天已经花费",
    "home.daily_budget": "今日预算",
    "home.remaining_today": "今天还剩 {amount} 可用。",
    "home.period_day": "日",
    "home.period_2weeks": "两周",
    "home.period_month": "月",
    "home.weekly_average": "本周平均",
    "home.prediction": "预测",
    "home.dashboard_title": "仪表板",
    "home.modal_add_title": "添加支出",
    "home.modal_remove_title": "取消支出",
    "home.modal_category": "类别",
    "home.modal_amount": "金额",
    "home.modal_amount_placeholder": "金额",
    
    // Budget Advisor
    "advisor.title": "预算顾问",
    "advisor.subtitle": "让我们创建您的个性化财务计划",
    "advisor.monthly_budget": "您的月预算是多少？",
    "advisor.rent": "您的月租金是多少？",
    "advisor.daily_spending": "您每天想花多少钱？",
    "advisor.weekly_spending": "您每周想花多少钱？",
    "advisor.biweekly_spending": "您每两周想花多少钱？",
    "advisor.monthly_spending": "您每月想花多少钱？",
    "advisor.savings_goal": "您的储蓄目标是什么？",
    "advisor.savings_30": "最大安全性（30%储蓄）",
    "advisor.savings_balanced": "平衡（15%储蓄）",
    "advisor.savings_invest": "投资（5%储蓄）",
    "advisor.calculate": "计算我的计划",
    "advisor.save": "保存",
    "advisor.continue": "继续",
    "advisor.back": "返回",
    "advisor.result_title": "您的预算计划",
    "advisor.fixed_charges": "固定费用",
    "advisor.available_spending": "可用于支出",
    "advisor.daily_budget": "每日预算",
    "advisor.weekly_budget": "每周预算",
    "advisor.biweekly_budget": "双周预算",
    
    // Settings
    "settings.title": "设置",
    "settings.currency": "货币",
    "settings.language": "语言",
    "settings.country": "国家",
    "settings.notifications": "通知",
    "settings.biometric": "生物识别认证",
    "settings.dark_mode": "深色模式",
    "settings.personal_info": "个人信息",
    "settings.logout": "退出登录",
    "settings.subtitle": "自定义您的体验",
    "settings.section_preferences": "偏好设置",
    "settings.section_security": "安全",
    "settings.section_appearance": "外观",
    "settings.section_account": "账户",
    "settings.section_actions": "操作",
    "settings.choose_language": "选择您的首选语言",
    "settings.choose_country": "选择您的国家",
    "settings.currency_modal_title": "选择货币",
    "settings.currency_modal_use_saved": "使用已保存计划的货币",
    "settings.push_notifications_title": "推送通知",
    "settings.push_notifications_subtitle": "接收支出提醒",
    "settings.biometric_title": "生物识别认证",
    "settings.biometric_subtitle": "使用 Face ID 或 Touch ID",
    "settings.dark_mode_title": "深色模式",
    "settings.dark_mode_subtitle": "启用深色主题",
    "settings.personal_info_title": "个人信息",
    "settings.personal_info_subtitle": "修改您的资料",
    "settings.personal_info_alert_title": "个人资料",
    "settings.personal_info_alert_body": "功能即将推出",
    "settings.logout_title": "退出登录",
    "settings.logout_subtitle": "退出您的账户",
    "settings.delete_account_title": "删除账户",
    "settings.delete_account_subtitle": "永久删除您的账户",
    
    // Common
    "common.save": "保存",
    "common.cancel": "取消",
    "common.confirm": "确认",
    "common.error": "错误",
    "common.success": "成功",
    "common.loading": "加载中...",
    "home.prediction_message_day_default": "今天的支出低于预期，继续保持！",
    "home.prediction_message_2weeks_default": "你目前的开销控制得很好。",
    "home.prediction_message_month_default": "本月可以争取多储蓄一些。",
    "home.category_food": "食物",
    "home.category_shopping": "购物",
    "home.category_leisure": "休闲",
    "details.title": "快速预算计划",
    "details.monthly_income_label": "每月收入 (EUR)",
    "details.monthly_income_placeholder": "例：2500",
    "details.savings_target_label": "每月储蓄目标",
    "details.savings_target_placeholder": "例：700",
    "details.calculate_button": "计算",
    "details.recommendations_title": "建议",
    "details.recommendations_monthly": "每月支出：{amount}",
    "details.recommendations_weekly": "每周支出：{amount}",
    "details.recommendations_daily": "每日支出：{amount}",
    "details.go_to_advisor": "查看详细计划",
  },
  
  ja: {
    // Navigation
    "nav.home": "ホーム",
    "nav.advisor": "アドバイザー",
    "nav.stats": "統計",
    "nav.settings": "設定",
    
    // Home Screen
    "home.title": "CashHeal",
    "home.subtitle": "スマートに財務を管理",
    "home.balance": "残高",
    "home.available": "利用可能",
    "home.spent": "支出",
    "home.budget": "予算",
    "home.add_expense": "支出を追加",
    "home.categories": "カテゴリ",
    "home.food": "食事",
    "home.shopping": "ショッピング",
    "home.leisure": "レジャー",
    "home.welcome_heading": "ようこそ！",
    "home.greeting": "こんにちは 👋",
    "home.welcome_subtitle": "家計を整える準備はできましたか？",
    "home.today_spent": "今日の支出",
    "home.daily_budget": "今日の予算",
    "home.remaining_today": "今日残りは {amount} です。",
    "home.period_day": "日",
    "home.period_2weeks": "2週間",
    "home.period_month": "月",
    "home.weekly_average": "今週の平均",
    "home.prediction": "予測",
    "home.dashboard_title": "ダッシュボード",
    "home.modal_add_title": "支出を追加",
    "home.modal_remove_title": "支出を取り消す",
    "home.modal_category": "カテゴリ",
    "home.modal_amount": "金額",
    "home.modal_amount_placeholder": "金額",
    
    // Budget Advisor
    "advisor.title": "予算アドバイザー",
    "advisor.subtitle": "あなたの個人的な財務計画を作成しましょう",
    "advisor.monthly_budget": "月間予算はいくらですか？",
    "advisor.rent": "月間家賃はいくらですか？",
    "advisor.daily_spending": "1日にいくら使いたいですか？",
    "advisor.weekly_spending": "週にいくら使いたいですか？",
    "advisor.biweekly_spending": "2週間ごとにいくら使いたいですか？",
    "advisor.monthly_spending": "月にいくら使いたいですか？",
    "advisor.savings_goal": "貯蓄目標は何ですか？",
    "advisor.savings_30": "最大セキュリティ（30%貯蓄）",
    "advisor.savings_balanced": "バランス（15%貯蓄）",
    "advisor.savings_invest": "投資（5%貯蓄）",
    "advisor.calculate": "私の計画を計算",
    "advisor.save": "保存",
    "advisor.continue": "続行",
    "advisor.back": "戻る",
    "advisor.result_title": "あなたの予算計画",
    "advisor.fixed_charges": "固定費",
    "advisor.available_spending": "支出可能額",
    "advisor.daily_budget": "日次予算",
    "advisor.weekly_budget": "週次予算",
    "advisor.biweekly_budget": "隔週予算",
    
    // Settings
    "settings.title": "設定",
    "settings.currency": "通貨",
    "settings.language": "言語",
    "settings.country": "国",
    "settings.notifications": "通知",
    "settings.biometric": "生体認証",
    "settings.dark_mode": "ダークモード",
    "settings.personal_info": "個人情報",
    "settings.logout": "ログアウト",
    "settings.subtitle": "体験をカスタマイズ",
    "settings.section_preferences": "基本設定",
    "settings.section_security": "セキュリティ",
    "settings.section_appearance": "外観",
    "settings.section_account": "アカウント",
    "settings.section_actions": "操作",
    "settings.choose_language": "希望の言語を選択してください",
    "settings.choose_country": "国を選択してください",
    "settings.currency_modal_title": "通貨を選択",
    "settings.currency_modal_use_saved": "保存されたプランの通貨を使用",
    "settings.push_notifications_title": "プッシュ通知",
    "settings.push_notifications_subtitle": "支出の通知を受け取る",
    "settings.biometric_title": "生体認証",
    "settings.biometric_subtitle": "Face ID / Touch ID を使用",
    "settings.dark_mode_title": "ダークモード",
    "settings.dark_mode_subtitle": "ダークテーマを有効にする",
    "settings.personal_info_title": "個人情報",
    "settings.personal_info_subtitle": "プロフィールを編集",
    "settings.personal_info_alert_title": "プロフィール",
    "settings.personal_info_alert_body": "近日公開",
    "settings.logout_title": "ログアウト",
    "settings.logout_subtitle": "アカウントからサインアウト",
    "settings.delete_account_title": "アカウント削除",
    "settings.delete_account_subtitle": "アカウントを完全に削除",
    
    // Common
    "common.save": "保存",
    "common.cancel": "キャンセル",
    "common.confirm": "確認",
    "common.error": "エラー",
    "common.success": "成功",
    "common.loading": "読み込み中...",
    "home.prediction_message_day_default": "今日は予定より出費が少なく、いい調子です！",
    "home.prediction_message_2weeks_default": "この調子なら予算内に収まりそうです。",
    "home.prediction_message_month_default": "今月はもう少し貯蓄を目指せます。",
    "home.category_food": "食事",
    "home.category_shopping": "ショッピング",
    "home.category_leisure": "レジャー",
    "details.title": "クイック予算プラン",
    "details.monthly_income_label": "月収 (EUR)",
    "details.monthly_income_placeholder": "例：2500",
    "details.savings_target_label": "月間貯蓄目標",
    "details.savings_target_placeholder": "例：700",
    "details.calculate_button": "計算する",
    "details.recommendations_title": "おすすめ",
    "details.recommendations_monthly": "月間支出：{amount}",
    "details.recommendations_weekly": "週間支出：{amount}",
    "details.recommendations_daily": "日次支出：{amount}",
    "details.go_to_advisor": "詳細プランを見る",
  },
};

const LanguageContext = createContext<LanguageCtx | null>(null);

const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("fr");

  useEffect(() => {
    (async () => {
      try {
        const stored = await storage.getItem(STORAGE_KEY);
        if (stored && SUPPORTED_LANGUAGES.includes(stored as Language)) {
          setLanguageState(stored as Language);
        }
      } catch (error) {
        console.warn("Impossible de charger la langue sauvegardée", error);
      }
    })();
  }, []);

  const setLanguage = useCallback(async (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    try {
      await storage.setItem(STORAGE_KEY, nextLanguage);
    } catch (error) {
      console.warn("Impossible d'enregistrer la langue", error);
    }
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export { LanguageProvider, SUPPORTED_LANGUAGES, LANGUAGE_NAMES, LANGUAGE_FLAGS };
